spring:
  application:
    name: marktview
  profiles:
    active: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG