version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-pdv
    environment:
      - MONGO_INITDB_DATABASE=marktview_db
    ports:
      - "27017:27017"
    volumes:
      - marktview-db-data:/data/db
    restart: always

volumes:
  marktview-db-data: